send_command:
  description: "Send a command to a Creality Control device."
  fields:
    target:
      description: "Select the Creality Control device."
      selector:
        target:
          entity:
            integration: creality_control
    printer_type:
      description: "Specify the type of printer (halot or wifi_box)."
      example: "halot"
      selector:
        select:
          options:
            - "halot"
            - "wifi_box"
    command:
      description: "The command to send to the device."
      example: "pause_resume_print"
      selector:
        select:
          options:
            - "pause_resume_print"
            - "stop_print"
